// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiu38jglAee1rc0T5nq5A6xqzSB9gXxWo',
    appId: '1:5220722592:web:dfddd52161a4affa1426c5',
    messagingSenderId: '5220722592',
    projectId: 'digital-addiction-tracker',
    authDomain: 'digital-addiction-tracker.firebaseapp.com',
    storageBucket: 'digital-addiction-tracker.firebasestorage.app',
    measurementId: 'G-PN2PXRG0DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8wUF9J3EosQECOw7K3v6L-czcZk1CuZw',
    appId: '1:5220722592:android:6f59e001c27168ae1426c5',
    messagingSenderId: '5220722592',
    projectId: 'digital-addiction-tracker',
    storageBucket: 'digital-addiction-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgjl7DvN5P3iu9e3qn4utkKDERzlycBo',
    appId: '1:5220722592:ios:fa906784a6b2a59e1426c5',
    messagingSenderId: '5220722592',
    projectId: 'digital-addiction-tracker',
    storageBucket: 'digital-addiction-tracker.firebasestorage.app',
    iosBundleId: 'com.example.addictionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBgjl7DvN5P3iu9e3qn4utkKDERzlycBo',
    appId: '1:5220722592:ios:fa906784a6b2a59e1426c5',
    messagingSenderId: '5220722592',
    projectId: 'digital-addiction-tracker',
    storageBucket: 'digital-addiction-tracker.firebasestorage.app',
    iosBundleId: 'com.example.addictionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiu38jglAee1rc0T5nq5A6xqzSB9gXxWo',
    appId: '1:5220722592:web:9d165fbecdbc61061426c5',
    messagingSenderId: '5220722592',
    projectId: 'digital-addiction-tracker',
    authDomain: 'digital-addiction-tracker.firebaseapp.com',
    storageBucket: 'digital-addiction-tracker.firebasestorage.app',
    measurementId: 'G-1T6QBQF3ZS',
  );
}
